package sbnz.integracija;

import sbnz.integracija.siem_center.facts.Log;
import sbnz.integracija.siem_center.facts.Alarm;
import sbnz.integracija.siem_center.facts.Risk;
import sbnz.integracija.siem_center.facts.MaliciousIps;

rule "Login error on same machine"
	when
		$log1: Log(type == "Login", status == "Error", $machine: machine, $time: time, $type: type)
		$log2: Log(type == "Login", status == "Error", machine.ip.equals($machine.ip), !time.equals($time))
	then
		System.out.println("Login error on same machine! \n\t" + $log1+ "\n\t" + $log2);
		insert(new Alarm($type, null, $machine, $time));
end
/*
rule "90 days inactive login attempt"
	when 
		$now: LocalDateTime()
		$log: Log(type == "Login", $now.compareTo(user.lastActivity) >= 90 )
	then
		System.out.println("Inactive user login attempt!" + $log);
		insert(new Alarm($log.getType(), $log.getUser(), $log.getMachine(), $log.getTime()));
end

rule "Malicious ip login attempt"
	when
		$mals: MaliciousIps() 
		$log: Log(type == "Login", machine.ip memberOf $mals)
	then
		System.out.println("Malicious ip login attempt!" + $log);
		insert(new Alarm($log.getType(), $log.getUser(), $log.getMachine(), $log.getTime()));
end

rule "Payment system attack"
	when
		$now: LocalDateTime()
		$logList : ArrayList(size > 50) from collect ( Log (time.isAfter($now.minusMinutes(1))))
	then
    	boolean isAttack = false;
    	int counter = 0;
    	for (Object el:$logList) {
    		Log log = (Log)el;
    		if (log.getType().equals("payment") {
    			counter = counter + 1;
    			if (counter > 50){
    				isAttack = true;
    				break;
    			}
    		}
    	}
    	if (isTypePayment) {
    		System.out.println("Payment system is attacked!");
        	insert(new Alarm("payment", null, null, null));
    	}
end

rule "Alarm"
	when
		$a: Alarm()
	then
		System.out.println("Alarm: " + $a);
end


rule "Error log"
	when
		$l: Log(status == LogStatus.Error)
	then
		System.out.println("ERROR log! " + $l);
		insert(new Alarm($l.getLogType(), $l.getUser(), $l.getMachine(), $l.getTime()))
end


rule "Login error with same user"
	when 
		$log1: Log(type == "Login", status == "Error", $user1: user, $type1: type, $time1: time)
		$log2: Log(type == "Login", status == "Error", user.username.equals($user1.username), $time2:time, !$time1.equals($time2))
	then 
		System.out.println("Login error for same user! \n\t" + $log1+ "\n\t" + $log2);
		insert(new Alarm($type1, $user1, null, $time2));
end

rule "15 login errors from same IP address in last 5 days"
	when
		$now: LocalDateTime()
		$logList: ArrayList(size > 15) from collect (
            Log(time.isAfter($now.minusDays(5)), type == "Login", status == "Error"))
    then
    	int sameIp;
    	String ip = "";
    	for (Object obj : &logList ){
    		sameIP  = 1;
    		Log log = (Log)obj;
    		ip = log.getMachine().getIp();
    		for (Object obj : &logList ){
	    		Log log2 = (Log)obj;
	    		if(ip.equals(log2.getMachine().getIp()) && !log.getTime().equals(log2.getTime())){
	    			sameIp++;
	    		}
	    	}
	    	if(sameIp >= 15){
		    	System.out.println("Login errors more than 15 times from same ip addres in past 5 days!"+
		    		log);
				insert(new Alarm("attack", null, log.getMachine(), log.getTime()));
				break;
			}    	
	    }
end

rule "Login error for malicious ip"
	when 
		$maliciousIps: MaliciousIps()
		$log: Log($maliciousIps.getIps().contains(machine.ip))
	then
		System.out.println("log with malicious ip"+log);
		insert(new Alarm("malicious", null, $log.getMachine(), log.getTime()));
end		
    	
rule "More than 6 threats registered for the same machine in last 10 days"
	when 
		$logList: ArrayList(size > 6) from collect (
            Log(Log.time.isAfter(LocalDateTime.now().minusDays(10)), type == "AntivirusReport", status == LogStatus.VirusThreat))
	then
		int sameIp;
    	String ip = "";
    	for (Object obj : &logList ){
    		sameIp  = 0;
    		Log log = (Log)obj;
    		ip = log.getMachine().getIp();
    		for (Object obj : &logList ){
	    		Log log2 = (Log)obj;
	    		if(ip.equals(log2.getMachine().getIp())){
	    			sameIp++;
	    		}
	    	}
	    	sameIp--;
	    	if(sameIp >= 7){
		    	System.out.println("More than 6 threats registered in the last 10 days on the same ip address "+
		    		log);
				insert(new Alarm(log.getType(), null, log.getMachine(), log.getTime()));
				break;
			}    	
	   
 end

 
 
rule "Antivirus threat not eliminated within hour"
	when
		$now: LocalDateTime()
		$log: Log(type =="antivirus", status == "VirusThreat", $now.isAfter(time.plusHours(1)))
		
	then	
end
*/